version: "3.9"

networks:
  dev:
    driver: bridge

services:
  art-gallery-api:
    image: docker.io/library/art-gallery-api
    depends_on:
      - "dev_db"
    container_name: art-gallery-api-services
    ports:
      - "7194:80"
    build:
      context: ./art-gallery-backend/art-gallery-backend/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=dev_db;User Id=postgres;Password=PostgreSQL;Port=5433;Database=art_gallery_db;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  dev_db:
    image: postgres:latest
    container_name: dev_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgreSQL
      - POSTGRES_DB=art_gallery_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./art-gallery-backend/art-gallery-backend/db_dump/art-gallery-db.sql:/docker-entrypoint-initdb.d/art-gallery-db.sql
    networks:
      - dev

  art-gallery-web:
    image: docker.io/library/art-gallery-web
    container_name: art-gallery-web-service
    ports:
      - "80:8080"
    build:
      context: ./art-gallery-frontend/
      dockerfile: Dockerfile
    networks:
      - dev

volumes:
  db_data:
  